// source: tendermint/types/block.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var gogoproto_gogo_pb = require('../../gogoproto/gogo_pb.js');
goog.object.extend(proto, gogoproto_gogo_pb);
var tendermint_types_types_pb = require('../../tendermint/types/types_pb.js');
goog.object.extend(proto, tendermint_types_types_pb);
var tendermint_types_evidence_pb = require('../../tendermint/types/evidence_pb.js');
goog.object.extend(proto, tendermint_types_evidence_pb);
goog.exportSymbol('proto.tendermint.types.Block', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tendermint.types.Block = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tendermint.types.Block, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tendermint.types.Block.displayName = 'proto.tendermint.types.Block';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tendermint.types.Block.prototype.toObject = function(opt_includeInstance) {
  return proto.tendermint.types.Block.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tendermint.types.Block} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tendermint.types.Block.toObject = function(includeInstance, msg) {
  var f, obj = {
    header: (f = msg.getHeader()) && tendermint_types_types_pb.Header.toObject(includeInstance, f),
    data: (f = msg.getData()) && tendermint_types_types_pb.Data.toObject(includeInstance, f),
    evidence: (f = msg.getEvidence()) && tendermint_types_evidence_pb.EvidenceList.toObject(includeInstance, f),
    lastCommit: (f = msg.getLastCommit()) && tendermint_types_types_pb.Commit.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tendermint.types.Block}
 */
proto.tendermint.types.Block.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tendermint.types.Block;
  return proto.tendermint.types.Block.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tendermint.types.Block} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tendermint.types.Block}
 */
proto.tendermint.types.Block.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new tendermint_types_types_pb.Header;
      reader.readMessage(value,tendermint_types_types_pb.Header.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 2:
      var value = new tendermint_types_types_pb.Data;
      reader.readMessage(value,tendermint_types_types_pb.Data.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    case 3:
      var value = new tendermint_types_evidence_pb.EvidenceList;
      reader.readMessage(value,tendermint_types_evidence_pb.EvidenceList.deserializeBinaryFromReader);
      msg.setEvidence(value);
      break;
    case 4:
      var value = new tendermint_types_types_pb.Commit;
      reader.readMessage(value,tendermint_types_types_pb.Commit.deserializeBinaryFromReader);
      msg.setLastCommit(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tendermint.types.Block.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tendermint.types.Block.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tendermint.types.Block} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tendermint.types.Block.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      tendermint_types_types_pb.Header.serializeBinaryToWriter
    );
  }
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      tendermint_types_types_pb.Data.serializeBinaryToWriter
    );
  }
  f = message.getEvidence();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      tendermint_types_evidence_pb.EvidenceList.serializeBinaryToWriter
    );
  }
  f = message.getLastCommit();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      tendermint_types_types_pb.Commit.serializeBinaryToWriter
    );
  }
};


/**
 * optional Header header = 1;
 * @return {?proto.tendermint.types.Header}
 */
proto.tendermint.types.Block.prototype.getHeader = function() {
  return /** @type{?proto.tendermint.types.Header} */ (
    jspb.Message.getWrapperField(this, tendermint_types_types_pb.Header, 1));
};


/**
 * @param {?proto.tendermint.types.Header|undefined} value
 * @return {!proto.tendermint.types.Block} returns this
*/
proto.tendermint.types.Block.prototype.setHeader = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tendermint.types.Block} returns this
 */
proto.tendermint.types.Block.prototype.clearHeader = function() {
  return this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tendermint.types.Block.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Data data = 2;
 * @return {?proto.tendermint.types.Data}
 */
proto.tendermint.types.Block.prototype.getData = function() {
  return /** @type{?proto.tendermint.types.Data} */ (
    jspb.Message.getWrapperField(this, tendermint_types_types_pb.Data, 2));
};


/**
 * @param {?proto.tendermint.types.Data|undefined} value
 * @return {!proto.tendermint.types.Block} returns this
*/
proto.tendermint.types.Block.prototype.setData = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tendermint.types.Block} returns this
 */
proto.tendermint.types.Block.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tendermint.types.Block.prototype.hasData = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional EvidenceList evidence = 3;
 * @return {?proto.tendermint.types.EvidenceList}
 */
proto.tendermint.types.Block.prototype.getEvidence = function() {
  return /** @type{?proto.tendermint.types.EvidenceList} */ (
    jspb.Message.getWrapperField(this, tendermint_types_evidence_pb.EvidenceList, 3));
};


/**
 * @param {?proto.tendermint.types.EvidenceList|undefined} value
 * @return {!proto.tendermint.types.Block} returns this
*/
proto.tendermint.types.Block.prototype.setEvidence = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tendermint.types.Block} returns this
 */
proto.tendermint.types.Block.prototype.clearEvidence = function() {
  return this.setEvidence(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tendermint.types.Block.prototype.hasEvidence = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Commit last_commit = 4;
 * @return {?proto.tendermint.types.Commit}
 */
proto.tendermint.types.Block.prototype.getLastCommit = function() {
  return /** @type{?proto.tendermint.types.Commit} */ (
    jspb.Message.getWrapperField(this, tendermint_types_types_pb.Commit, 4));
};


/**
 * @param {?proto.tendermint.types.Commit|undefined} value
 * @return {!proto.tendermint.types.Block} returns this
*/
proto.tendermint.types.Block.prototype.setLastCommit = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tendermint.types.Block} returns this
 */
proto.tendermint.types.Block.prototype.clearLastCommit = function() {
  return this.setLastCommit(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tendermint.types.Block.prototype.hasLastCommit = function() {
  return jspb.Message.getField(this, 4) != null;
};


goog.object.extend(exports, proto.tendermint.types);
